---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver
  namespace: ws3
  labels:
    app: ws3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws3
  template:
    metadata:
      name: codeserver-po
      labels:
        app: ws3
    spec:
      containers:
      - name: ws3-container
        image: linuxserver/code-server:latest
        imagePullPolicy: IfNotPresent
        
        envFrom:
          - configMapRef:
              name: ws3cm
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: workspace
          mountPath: "/config/workspace"
          readOnly: true
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace-pvc
        

        #readinessProbe:
          #httpGet:
            #path: /healthz
            #port: 3000
        #livenessProbe:
          #httpGet:
            #path: /healthz
            #port: 3000
          #periodSeconds: 30
          #successThreshold: 1
          #timeoutSeconds: 5
            
      
---

apiVersion: v1
kind: Service
metadata:
  name: codeserver-svc
  namespace: ws3
  labels:
    app: ws3     
spec:    
  #type: NodePort
  #type: LoadBalancer
  type: ClusterIP
  selector:
    app: ws3
  ports:
  - port: 8443
    targetPort: 8443
    

      