---
apiVersion: v1
kind: Namespace
metadata:
  name: ws3
  labels:
    name: ws3
        
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc
  namespace: ws3
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi