---
apiVersion: v1
kind: Pod
metadata:
  name: dov-pod-0
  namespace: myns
  labels:
    app: dov
spec:
  containers:
  - name: dov-container
    image: chukmunnlee/dov-bear:v5 
    imagePullPolicy: IfNotPresent
    env:
    - name: INSTANCE_NAME
      value: "Test"
    - name: INSTANCE_NAME
      valueFrom: 
       fieldRef:
        fieldPath: status.podIP
    ports:
    - containerPort: 3000
    #command: ["echo"]
    #args: ["Hello World"]