---
apiVersion: v1
kind: Secret
metadata:
  name: dov-secret
  namespace: myns
  labels:
    app: dov
type: Opaque
data: 
  INSTANCE_NAME: VGhpcyBpcyBhIFNlY3JldA==
  DB_PASSWORD: Y2hhbmdlaXQ=
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deployment
  namespace: myns
  labels:
    app: dov
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dov
  template:
    metadata:
      name: dov-po
      labels:
        app: dov
    spec:
      containers:
      - name: dov-container
        image: chukmunnlee/dov-bear:v5 
        imagePullPolicy: IfNotPresent
        
        env:
        #- name: INSTANCE_NAME
          #value: "Test"
        - name: INSTANCE_HASH
          valueFrom: 
           fieldRef:
            fieldPath: status.podIP
        envFrom:
        - secretRef:        
            name: dov-secret
        ports:
        - containerPort: 3000
        #readinessProbe:
          #httpGet:
            #path: /healthz
            #port: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
            
      
---

apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: myns
  labels:
    app: dov     
spec:    
  type: NodePort
  selector:
    app: dov
  ports:
  - port: 9099
    targetPort: 3000
    
    