---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws2-app
  namespace: ws2
  labels:
    app: ws2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ws2
  template:
    metadata:
      name: ws2app-po
      labels:
        app: ws2
    spec:
      containers:
      - name: ws2-container
        image: stackupiss/bgg-backend:v1 
        imagePullPolicy: IfNotPresent
        
        env:
        - name: BGG_DB_USER 
          valueFrom:
            configMapKeyRef:
              name: ws2cm           
              key: BGG_DB_USER 
        - name: BGG_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ws2cm
              key: BGG_DB_HOST
        - name: INSTANCE_HASH
          valueFrom: 
           fieldRef:
            fieldPath: status.podIP
        envFrom:
        - secretRef:        
            name: ws2-secret
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
            
      
---

apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: ws2
  labels:
    app: ws2     
spec:    
  type: NodePort
  #type: ClusterIP
  selector:
    app: ws2
  ports:
  - port: 9099
    targetPort: 3000
    
    