---
apiVersion: v1
kind: Namespace
metadata:
  name: ws2
  labels:
    name: ws2
---
apiVersion: v1
kind: Secret
metadata:
  name: ws2-secret
  namespace: ws2
  labels:
    app: ws2
type: Opaque
data:   
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ws2cm
  namespace: ws2
data:
  BGG_DB_USER: "root"    
  BGG_DB_HOST: "mydb-svc"

