---
apiVersion: v1
kind: Namespace
metadata:
  name: ws4
  labels:
    name: ws4
        
---
apiVersion: v1
kind: PersistentVolumeClaim
volumeClaimTemplates:
metadata:
  name: data-pvc
  namespace: ws4
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi